### ISSUE TITLE
How do I install it in Windows?

### ISSUE THREAD

**Issue by jldelda** [wjk/BFG-Windows#1]
I don't know how to install it in Windows. Could you help me?

**Comment by wjk** [comment]
Did you read [the instructions I posted on the release page](https://github.com/wjk/BFG-Windows/releases/tag/v1.13.0)? 😉 

In all seriousness, simply download the two files in the release, place them in the same directory, and ensure that the prerequisites (Java 1.8 and the Visual Studio 2017 C++ runtime) are installed. No other configuration is required; BFG will then launch from a Command Prompt. (If Java 1.8 is missing, BFG.exe will fail gracefully. If the C++ runtime is missing, it will fail less than gracefully. Unfortunately, I cannot control the latter case.) Using Chocolatey is more convenient, but much harder to explain. If you still are having trouble, please post a reply and I'll take a look at it. Thanks!

**Comment by jldelda** [comment]
It's a pity I am on a computer in a secure network so I cannot install the requirements. 

I sent you a pull request with that information in the Readme though. Thank you very much, I think it was clear, but I had not seen the Release page.

**Comment by jldelda** [comment]
Here there is a template for gituhb repos that you may like: https://github.com/EL-BID/Plantilla-de-repositorio/blob/master/README-EN.md
