### ISSUE TITLE
Change chocolatey dependency to OpenJDK from Oracle Java

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [wjk/BFG-Windows#3]
Due to Oracle licensing changes prohibiting business use.

I would suggest switching the nuspec JRE dependency to an AdoptOpenJDK JRE build, probably this one- https://chocolatey.org/packages/adoptopenjdk8jre

**Comment by wjk** [comment]
Thanks for reaching out! I'll probably look at this later today. Thanks!

**Comment by TheCakeIsNaOH** [comment]
Wonderful, thank you for your very quick response.
